upgrade to org.locationtech.jts
bedatadriven/jackson-datatype-jts pull request #18
Opened 2018-01-15 22:13 UTC by karussell

2018-06-21 01:26 UTC, Sarev0k commented
@akbertram @purpleP Would it be possible for you to merge this and kick off a new release?

I'd like to consume the latest version of JTS, and this is blocking me.

2018-06-21 07:21 UTC, karussell commented
See https://github.com/graphhopper/jackson-datatype-jts/ and also [here](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.graphhopper.external%22%20AND%20a%3A%22jackson-datatype-jts%22) for a bug fix release.

2018-10-23 07:13 UTC, ernstdevreede commented
Can we expect this very useful PR for switching to org.locationtech.jts package to be merged soon?
Otherwise I might want to clone the project.

2018-10-31 17:39 UTC, russellhoff commented
Really interesting PR. Please go on! Thank you so much.

2019-01-24 12:21 UTC, roryodonnell commented
I can confirm this issue as I'm also experiencing it
```
[INFO] +- com.bedatadriven:jackson-datatype-jts:jar:2.4:compile
[INFO] |  \- com.vividsolutions:jts:jar:1.13:compile
```
which causes the follow hibernate type bindings
```
DEBUG [2019-01-24 12:02:52,816] org.hibernate.type.BasicTypeRegistry: Adding type registration com.vividsolutions.jts.geom.Point -> org.hibernate.spatial.JTSGeometryType@3a0e7f89
```
...when I try to persist entity containing `org.locationtech.jts.geom.Point` I get a Postgres endian issue.

2019-02-26 15:53 UTC, herekkratz requested changes
Looks good to me, except for the two proposed changes.

2019-02-26 15:53 UTC, herekkratz commented on pom.xml
>        <version>2.4.2</version>
The incompatibility justifies a major version increment.
```suggestion
      <version>2.5.0</version>
```

2019-02-26 15:53 UTC, herekkratz commented on pom.xml
> +      <version>1.15.0</version>
```suggestion
      <version>1.16.0</version>
```

2019-02-27 07:42 UTC, russellhoff commented
How can I lend a hand?

2019-03-08 08:58 UTC, BartoszKaszewczuk commented
Any reason why this wasn't merged yet?

2019-03-08 09:11 UTC, purpleP commented
Guys, I don't have motivation to work on this and even if I would I don't think I can upload new releases to maven central etc.

If I would maintain this library I would do this

- use gradle as a build tool
- use property based testing instead of or along with existing tests.

2019-06-18 12:54 UTC, larsnaesbye approved these changes

2022-11-21 11:17 UTC, closed without merging